[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "backend>=0.2.4.1",
    "dotenv>=0.9.9",
    "pymupdf>=1.26.4",
    "streamlit>=1.49.1",
]
